/*
 * cityfalcon
 *
 * cityfalcon API
 *
 * API version: 1.0.0
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// MetadataRegularGlobalAttributes struct for MetadataRegularGlobalAttributes
type MetadataRegularGlobalAttributes struct {
	AssetClassPopular        *string `json:"assetClassPopular,omitempty"`
	AssetClassName           *string `json:"assetClassName,omitempty"`
	AssetClassOrder          *string `json:"assetClassOrder,omitempty"`
	AssetClassSearchPriority *string `json:"assetClassSearchPriority,omitempty"`
	AssetClassSlug           *string `json:"assetClassSlug,omitempty"`
	AssetClassTitle          *string `json:"assetClassTitle,omitempty"`
	Popular                  *string `json:"popular,omitempty"`
	AssetClassId             *string `json:"assetClassId,omitempty"`
	AssetClassKind           *string `json:"assetClassKind,omitempty"`
}

// NewMetadataRegularGlobalAttributes instantiates a new MetadataRegularGlobalAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMetadataRegularGlobalAttributes() *MetadataRegularGlobalAttributes {
	this := MetadataRegularGlobalAttributes{}
	return &this
}

// NewMetadataRegularGlobalAttributesWithDefaults instantiates a new MetadataRegularGlobalAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMetadataRegularGlobalAttributesWithDefaults() *MetadataRegularGlobalAttributes {
	this := MetadataRegularGlobalAttributes{}
	return &this
}

// GetAssetClassPopular returns the AssetClassPopular field value if set, zero value otherwise.
func (o *MetadataRegularGlobalAttributes) GetAssetClassPopular() string {
	if o == nil || o.AssetClassPopular == nil {
		var ret string
		return ret
	}
	return *o.AssetClassPopular
}

// GetAssetClassPopularOk returns a tuple with the AssetClassPopular field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataRegularGlobalAttributes) GetAssetClassPopularOk() (*string, bool) {
	if o == nil || o.AssetClassPopular == nil {
		return nil, false
	}
	return o.AssetClassPopular, true
}

// HasAssetClassPopular returns a boolean if a field has been set.
func (o *MetadataRegularGlobalAttributes) HasAssetClassPopular() bool {
	if o != nil && o.AssetClassPopular != nil {
		return true
	}

	return false
}

// SetAssetClassPopular gets a reference to the given string and assigns it to the AssetClassPopular field.
func (o *MetadataRegularGlobalAttributes) SetAssetClassPopular(v string) {
	o.AssetClassPopular = &v
}

// GetAssetClassName returns the AssetClassName field value if set, zero value otherwise.
func (o *MetadataRegularGlobalAttributes) GetAssetClassName() string {
	if o == nil || o.AssetClassName == nil {
		var ret string
		return ret
	}
	return *o.AssetClassName
}

// GetAssetClassNameOk returns a tuple with the AssetClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataRegularGlobalAttributes) GetAssetClassNameOk() (*string, bool) {
	if o == nil || o.AssetClassName == nil {
		return nil, false
	}
	return o.AssetClassName, true
}

// HasAssetClassName returns a boolean if a field has been set.
func (o *MetadataRegularGlobalAttributes) HasAssetClassName() bool {
	if o != nil && o.AssetClassName != nil {
		return true
	}

	return false
}

// SetAssetClassName gets a reference to the given string and assigns it to the AssetClassName field.
func (o *MetadataRegularGlobalAttributes) SetAssetClassName(v string) {
	o.AssetClassName = &v
}

// GetAssetClassOrder returns the AssetClassOrder field value if set, zero value otherwise.
func (o *MetadataRegularGlobalAttributes) GetAssetClassOrder() string {
	if o == nil || o.AssetClassOrder == nil {
		var ret string
		return ret
	}
	return *o.AssetClassOrder
}

// GetAssetClassOrderOk returns a tuple with the AssetClassOrder field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataRegularGlobalAttributes) GetAssetClassOrderOk() (*string, bool) {
	if o == nil || o.AssetClassOrder == nil {
		return nil, false
	}
	return o.AssetClassOrder, true
}

// HasAssetClassOrder returns a boolean if a field has been set.
func (o *MetadataRegularGlobalAttributes) HasAssetClassOrder() bool {
	if o != nil && o.AssetClassOrder != nil {
		return true
	}

	return false
}

// SetAssetClassOrder gets a reference to the given string and assigns it to the AssetClassOrder field.
func (o *MetadataRegularGlobalAttributes) SetAssetClassOrder(v string) {
	o.AssetClassOrder = &v
}

// GetAssetClassSearchPriority returns the AssetClassSearchPriority field value if set, zero value otherwise.
func (o *MetadataRegularGlobalAttributes) GetAssetClassSearchPriority() string {
	if o == nil || o.AssetClassSearchPriority == nil {
		var ret string
		return ret
	}
	return *o.AssetClassSearchPriority
}

// GetAssetClassSearchPriorityOk returns a tuple with the AssetClassSearchPriority field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataRegularGlobalAttributes) GetAssetClassSearchPriorityOk() (*string, bool) {
	if o == nil || o.AssetClassSearchPriority == nil {
		return nil, false
	}
	return o.AssetClassSearchPriority, true
}

// HasAssetClassSearchPriority returns a boolean if a field has been set.
func (o *MetadataRegularGlobalAttributes) HasAssetClassSearchPriority() bool {
	if o != nil && o.AssetClassSearchPriority != nil {
		return true
	}

	return false
}

// SetAssetClassSearchPriority gets a reference to the given string and assigns it to the AssetClassSearchPriority field.
func (o *MetadataRegularGlobalAttributes) SetAssetClassSearchPriority(v string) {
	o.AssetClassSearchPriority = &v
}

// GetAssetClassSlug returns the AssetClassSlug field value if set, zero value otherwise.
func (o *MetadataRegularGlobalAttributes) GetAssetClassSlug() string {
	if o == nil || o.AssetClassSlug == nil {
		var ret string
		return ret
	}
	return *o.AssetClassSlug
}

// GetAssetClassSlugOk returns a tuple with the AssetClassSlug field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataRegularGlobalAttributes) GetAssetClassSlugOk() (*string, bool) {
	if o == nil || o.AssetClassSlug == nil {
		return nil, false
	}
	return o.AssetClassSlug, true
}

// HasAssetClassSlug returns a boolean if a field has been set.
func (o *MetadataRegularGlobalAttributes) HasAssetClassSlug() bool {
	if o != nil && o.AssetClassSlug != nil {
		return true
	}

	return false
}

// SetAssetClassSlug gets a reference to the given string and assigns it to the AssetClassSlug field.
func (o *MetadataRegularGlobalAttributes) SetAssetClassSlug(v string) {
	o.AssetClassSlug = &v
}

// GetAssetClassTitle returns the AssetClassTitle field value if set, zero value otherwise.
func (o *MetadataRegularGlobalAttributes) GetAssetClassTitle() string {
	if o == nil || o.AssetClassTitle == nil {
		var ret string
		return ret
	}
	return *o.AssetClassTitle
}

// GetAssetClassTitleOk returns a tuple with the AssetClassTitle field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataRegularGlobalAttributes) GetAssetClassTitleOk() (*string, bool) {
	if o == nil || o.AssetClassTitle == nil {
		return nil, false
	}
	return o.AssetClassTitle, true
}

// HasAssetClassTitle returns a boolean if a field has been set.
func (o *MetadataRegularGlobalAttributes) HasAssetClassTitle() bool {
	if o != nil && o.AssetClassTitle != nil {
		return true
	}

	return false
}

// SetAssetClassTitle gets a reference to the given string and assigns it to the AssetClassTitle field.
func (o *MetadataRegularGlobalAttributes) SetAssetClassTitle(v string) {
	o.AssetClassTitle = &v
}

// GetPopular returns the Popular field value if set, zero value otherwise.
func (o *MetadataRegularGlobalAttributes) GetPopular() string {
	if o == nil || o.Popular == nil {
		var ret string
		return ret
	}
	return *o.Popular
}

// GetPopularOk returns a tuple with the Popular field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataRegularGlobalAttributes) GetPopularOk() (*string, bool) {
	if o == nil || o.Popular == nil {
		return nil, false
	}
	return o.Popular, true
}

// HasPopular returns a boolean if a field has been set.
func (o *MetadataRegularGlobalAttributes) HasPopular() bool {
	if o != nil && o.Popular != nil {
		return true
	}

	return false
}

// SetPopular gets a reference to the given string and assigns it to the Popular field.
func (o *MetadataRegularGlobalAttributes) SetPopular(v string) {
	o.Popular = &v
}

// GetAssetClassId returns the AssetClassId field value if set, zero value otherwise.
func (o *MetadataRegularGlobalAttributes) GetAssetClassId() string {
	if o == nil || o.AssetClassId == nil {
		var ret string
		return ret
	}
	return *o.AssetClassId
}

// GetAssetClassIdOk returns a tuple with the AssetClassId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataRegularGlobalAttributes) GetAssetClassIdOk() (*string, bool) {
	if o == nil || o.AssetClassId == nil {
		return nil, false
	}
	return o.AssetClassId, true
}

// HasAssetClassId returns a boolean if a field has been set.
func (o *MetadataRegularGlobalAttributes) HasAssetClassId() bool {
	if o != nil && o.AssetClassId != nil {
		return true
	}

	return false
}

// SetAssetClassId gets a reference to the given string and assigns it to the AssetClassId field.
func (o *MetadataRegularGlobalAttributes) SetAssetClassId(v string) {
	o.AssetClassId = &v
}

// GetAssetClassKind returns the AssetClassKind field value if set, zero value otherwise.
func (o *MetadataRegularGlobalAttributes) GetAssetClassKind() string {
	if o == nil || o.AssetClassKind == nil {
		var ret string
		return ret
	}
	return *o.AssetClassKind
}

// GetAssetClassKindOk returns a tuple with the AssetClassKind field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MetadataRegularGlobalAttributes) GetAssetClassKindOk() (*string, bool) {
	if o == nil || o.AssetClassKind == nil {
		return nil, false
	}
	return o.AssetClassKind, true
}

// HasAssetClassKind returns a boolean if a field has been set.
func (o *MetadataRegularGlobalAttributes) HasAssetClassKind() bool {
	if o != nil && o.AssetClassKind != nil {
		return true
	}

	return false
}

// SetAssetClassKind gets a reference to the given string and assigns it to the AssetClassKind field.
func (o *MetadataRegularGlobalAttributes) SetAssetClassKind(v string) {
	o.AssetClassKind = &v
}

func (o MetadataRegularGlobalAttributes) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AssetClassPopular != nil {
		toSerialize["assetClassPopular"] = o.AssetClassPopular
	}
	if o.AssetClassName != nil {
		toSerialize["assetClassName"] = o.AssetClassName
	}
	if o.AssetClassOrder != nil {
		toSerialize["assetClassOrder"] = o.AssetClassOrder
	}
	if o.AssetClassSearchPriority != nil {
		toSerialize["assetClassSearchPriority"] = o.AssetClassSearchPriority
	}
	if o.AssetClassSlug != nil {
		toSerialize["assetClassSlug"] = o.AssetClassSlug
	}
	if o.AssetClassTitle != nil {
		toSerialize["assetClassTitle"] = o.AssetClassTitle
	}
	if o.Popular != nil {
		toSerialize["popular"] = o.Popular
	}
	if o.AssetClassId != nil {
		toSerialize["assetClassId"] = o.AssetClassId
	}
	if o.AssetClassKind != nil {
		toSerialize["assetClassKind"] = o.AssetClassKind
	}
	return json.Marshal(toSerialize)
}

type NullableMetadataRegularGlobalAttributes struct {
	value *MetadataRegularGlobalAttributes
	isSet bool
}

func (v NullableMetadataRegularGlobalAttributes) Get() *MetadataRegularGlobalAttributes {
	return v.value
}

func (v *NullableMetadataRegularGlobalAttributes) Set(val *MetadataRegularGlobalAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableMetadataRegularGlobalAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableMetadataRegularGlobalAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMetadataRegularGlobalAttributes(val *MetadataRegularGlobalAttributes) *NullableMetadataRegularGlobalAttributes {
	return &NullableMetadataRegularGlobalAttributes{value: val, isSet: true}
}

func (v NullableMetadataRegularGlobalAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMetadataRegularGlobalAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
